// Package xodb contains the types for schema 'app_mvp_dating'.
package xodb

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// Status is the 'status' enum type from schema 'app_mvp_dating'.
type Status uint16

const (
	// StatusSingle is the 'single' Status.
	StatusSingle = Status(1)

	// StatusDivorce is the 'divorce' Status.
	StatusDivorce = Status(2)

	// StatusComplicate is the 'complicate' Status.
	StatusComplicate = Status(3)
)

// String returns the string value of the Status.
func (s Status) String() string {
	var enumVal string

	switch s {
	case StatusSingle:
		enumVal = "single"

	case StatusDivorce:
		enumVal = "divorce"

	case StatusComplicate:
		enumVal = "complicate"
	}

	return enumVal
}

// MarshalText marshals Status into text.
func (s Status) MarshalText() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalText unmarshals Status from text.
func (s *Status) UnmarshalText(text []byte) error {
	switch string(text) {
	case "single":
		*s = StatusSingle

	case "divorce":
		*s = StatusDivorce

	case "complicate":
		*s = StatusComplicate

	default:
		return errors.New("invalid Status")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for Status.
func (s Status) Value() (driver.Value, error) {
	return s.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for Status.
func (s *Status) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid Status")
	}

	return s.UnmarshalText(buf)
}
